services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: ems-jenkins
    user: root # Ensure Jenkins runs with sufficient privileges
    build:
      context: .
      dockerfile: Dockerfile # Add Docker and Compose to Jenkins container
    volumes:
      - /var/jenkins_home:/var/jenkins_home # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Share Docker socket
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Point Jenkins to the host's Docker daemon
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
    ports:
      - "8085:8080" # Expose Jenkins on localhost:8085
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
